name: news001
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  shimmer: ^3.0.0
  flutter_tts: ^4.2.3
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


flutter_icons:
  android: true
  ios: true
  image_path: "assets/news.png"
  adaptive_icon_background: "#fffff"
  adaptive_icon_foreground: "assets/Icon-iPhone-180.png"



  assets:
    - assets/Audio_Wave.json
